### DISCUSSION TITLE
Handling with low traffic services in SLOs

### DISCUSSION THREAD

**Discussion by gagbo** [autometrics-dev/autometrics-shared#53] [General]
While trying to find information about reducing the NaN in the to-be-released autometrics grafana dashboard, I found how to make sloth generated SLIs ignore datapoints when the count of events do not meet a threshold I think https://github.com/autometrics-dev/autometrics-rs/pull/56/commits/1bd54d92d3212e38c0e83bdaaf378020fa61f225

If instead of `> 0` we use `> count` we should be able to force a threshold of “minimum events to trigger an alert” from my understanding. But I don’t know what value should be added there if not 0, because it might not be valid for most projects. Should we use a default value ourself? Should we just ask for a threshold on generation?

**Comment by gagbo** [comment]
One solution I like would be to use [`increase`](https://prometheus.io/docs/prometheus/latest/querying/functions/#increase) instead of `rate` operator for our queries, and make the generated sloth file find a way to threshold all SLIs so that a single failure doesn't consume the full error budget:

```
  - name: latency-99
    objective: 99
    description: Common SLO based on function latency
    sli:
      events:
        error_query: >
          sum by (objective_name, objective_percentile) (increase(function_calls_duration_count{objective_percentile="99"}[{{.window}}]))
          -
          (sum by (objective_name, objective_percentile) (
            label_join(increase(function_calls_duration_bucket{objective_percentile="99"}[{{.window}}]), "autometrics_check_label_equality", "", "objective_latency_threshold")
            and
            label_join(increase(function_calls_duration_bucket{objective_percentile="99"}[{{.window}}]), "autometrics_check_label_equality", "", "le")
          ))
        total_query: sum by (objective_name, objective_percentile) (increase(function_calls_duration_count{objective_percentile="99"}[{{.window}}])) > 100
    alerting:
      name: High Latency SLO - 99%
      labels:
        category: latency
      annotations:
        summary: "High latency on SLO: {{$labels.objective_name}}"
      page_alert:
        labels:
          severity: page
      ticket_alert:
        labels:
          severity: ticket
```

In the `total_query` line, the `100` threshold is obtained as :
```rust
let sli_threshold = 100.0 / (100.0 - objective)
```

So the threshold for the current builtin values would be
```
90% -> 10
95% -> 20
99% -> 100
99.9% -> 1000
```
The `>` (rather than `>=`) should ensure that 1 failure is still below the threshold.
